OPENAI_API_KEY = "sk-PL5QdXFgcWOeUViElFs_l-NVBFdeSI8NaMxdJkgSGeT3BlbkFJNmN9d9jCcc9PQVrAt52evEMlDdrebZqH4dqfUL2hEA"
OPENAI_MODEL = "gpt-4o-mini"

NEO4J_URI = "bolt://localhost:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "12345678"

